// Biblioteca de requisitos do Planejador de Experimentos Hydrone.
// Cada bloco pertence a uma categoria de experimento (categoria: "manobra" | "bancada" | "veiculo").
// Cada item tem uma explicação simples (sempre visível) e um detalhe técnico
// (escondido atrás do botão "detalhe técnico"): o que ele gera e por que importa.
//
// captura: como o item é preenchido durante o ensaio.
//   "valor"    → campo de texto/número (vira coluna na planilha de campo, se escopo = "ensaio")
//   "status"   → Passou / Falhou / N/A
//   "tarefa"   → Feito / Pendente / N/A
// escopo: "sessao" (checado uma vez, no protocolo) ou "ensaio" (repetido a cada ensaio → planilha de campo)

export const CAPTURAS = {
  status: { label: "Verificação", opcoes: ["Passou", "Falhou", "N/A"] },
  tarefa: { label: "Tarefa", opcoes: ["Feito", "Pendente", "N/A"] },
  valor: { label: "Valor", opcoes: [] },
};

// Categorias de experimento — cada bloco da biblioteca pertence a uma delas.
export const CATEGORIAS = [
  {
    id: "manobra",
    label: "Manobra de pouso · HUAUV/USV",
    descricao: "Impacto do pouso, resposta do casco e sincronismo entre controladoras.",
    icone: "Waves",
  },
  {
    id: "bancada",
    label: "Bancada de propulsão bimodal",
    descricao: "Empuxo, torque, corrente e eficiência dos propulsores na bancada.",
    icone: "Gauge",
  },
  {
    id: "veiculo",
    label: "Veículo Hydrone-J em campo",
    descricao: "Consumo e telemetria da missão híbrida, etapa por etapa.",
    icone: "Rocket",
  },
];
export const CATEGORIA_PADRAO = "manobra";

let _iid = 0;
const uid = () => `r${Date.now().toString(36)}${(_iid++).toString(36)}`;

const it = (id, titulo, simples, gera, porque, captura, escopo, unidade = "") =>
  ({ id, titulo, simples, gera, porque, captura, escopo, unidade });

export const BLOCOS_PADRAO = [
  {
    id: "A", titulo: "Base de tempo comum", core: true, categoria: "manobra",
    resumo: "Fazer os sensores e as controladoras concordarem sobre \"quando\" cada coisa aconteceu.",
    itens: [
      it("A1", "Marco de sincronismo (3 batidas)",
        "No começo e no fim de cada ensaio, dê três batidas secas na estrutura do veículo. Isso cria um \"marco\" que os sensores registram, para alinhar no tempo os dados de controladoras diferentes.",
        "Um evento impulsivo reconhecível na aceleração de cada log, usado para calcular o deslocamento entre os relógios internos de cada controladora.",
        "Cada controladora conta o tempo do seu próprio jeito (em geral, desde que ligou). Sem um marco físico comum, não dá para saber se o instante \"12,3 s\" de um log é o mesmo instante do outro.",
        "tarefa", "ensaio"),
      it("A2", "Fonte única de tempo de referência (GPS)",
        "Antes de começar, confirme que todas as controladoras usam a mesma referência de tempo — o relógio do GPS. Assim dá para comparar quando cada uma registrou algo sem precisar fazer contas.",
        "Timestamps absolutos comparáveis entre logs de diferentes computadores de bordo.",
        "Se cada controladora usa seu próprio relógio interno, um atraso de poucos segundos entre ligar uma e outra já desalinha todo o resto dos dados.",
        "status", "sessao"),
      it("A3", "Timestamp absoluto no log",
        "Confira que o log grava a hora real (dia, hora, minuto, segundo), e não só \"segundos desde que ligou\". Só a hora real permite comparar ensaios de dias diferentes.",
        "Campo de data/hora absoluta em cada linha do log, em vez de um contador relativo ao boot.",
        "Um contador relativo reinicia a cada religada, o que impede juntar ou comparar ensaios feitos em sessões diferentes.",
        "status", "sessao"),
      it("A4", "Taxa de amostragem real do log",
        "Depois de um ensaio de teste, abra o log e confira quantas leituras por segundo ele realmente gravou. Às vezes o que está configurado no papel não é o que sai de fato no arquivo.",
        "Confirmação da taxa de amostragem efetiva (Hz) de cada sensor gravado.",
        "Se a taxa real for menor que a esperada, eventos rápidos (como o impacto do pouso) podem não ser capturados direito.",
        "valor", "sessao", "Hz"),
      it("A5", "Deriva de relógio entre controladoras",
        "Em ensaios longos, o relógio de uma controladora pode ir se atrasando ou adiantando em relação à outra. Compare o intervalo entre as batidas de sincronismo do início e do fim em cada log.",
        "Estimativa do desvio (drift) acumulado entre os relógios das controladoras ao longo do ensaio.",
        "Um desvio grande faz o alinhamento pelo marco do início parecer bom, mas ir se perdendo ao longo do ensaio.",
        "valor", "ensaio", "ms"),
    ],
  },
  {
    id: "B", titulo: "Medir a entrada / perturbação do pouso", core: true, categoria: "manobra",
    resumo: "Registrar como o veículo chegou na água — a \"causa\" que depois se compara com a resposta do casco.",
    itens: [
      it("B1", "Velocidade vertical no toque com a água",
        "Registre a que velocidade o veículo estava descendo no instante exato em que tocou a água. É essa velocidade que \"agita\" o casco — quanto mais rápido o pouso, maior o impacto.",
        "Componente vertical da velocidade (m/s) no instante de contato, extraída do log de altitude/IMU.",
        "É a principal variável de entrada do fenômeno de pouso; sem ela não dá para relacionar \"o que causou\" com \"o que o casco fez depois\".",
        "valor", "ensaio", "m/s"),
      it("B2", "Ângulo de aproximação no toque",
        "Anote a inclinação do veículo (para frente/trás e para os lados) no momento do toque com a água. Um pouso torto agita o casco de um jeito diferente de um pouso nivelado.",
        "Pitch e roll (°) no instante de contato, extraídos do IMU.",
        "O ângulo de entrada muda a área de contato e a distribuição da força de impacto no casco.",
        "valor", "ensaio", "°"),
      it("B3", "Estado do mar no momento do pouso",
        "Descreva como estava a água na hora do pouso (parada, com ondulação leve, com ondas). Isso também empurra o casco e pode se misturar com o efeito que você está tentando medir.",
        "Registro qualitativo/quantitativo do estado do mar simultâneo ao evento de pouso (não apenas a condição geral do dia).",
        "Ondas presentes exatamente no instante do pouso são uma perturbação adicional que pode ser confundida com a resposta ao próprio pouso.",
        "valor", "ensaio"),
      it("B4", "Vídeo do pouso",
        "Grave um vídeo do momento do pouso. Se depois os números do sensor parecerem estranhos, o vídeo ajuda a entender o que aconteceu de verdade.",
        "Registro visual sincronizável (pelo marco de A1) com os dados numéricos do pouso.",
        "Números isolados não mostram causas incomuns (rajada de vento, pouso torto por engano); o vídeo serve de checagem cruzada.",
        "tarefa", "ensaio"),
    ],
  },
  {
    id: "C", titulo: "Medir a resposta do casco", core: true, categoria: "manobra",
    resumo: "Registrar como o casco reage depois do pouso — o \"efeito\" a explicar.",
    itens: [
      it("C1", "Aceleração vertical do casco",
        "Registre como a aceleração vertical do casco se comporta nos segundos seguintes ao pouso — é o \"chacoalhar\" que você quer entender.",
        "Série temporal de aceleração vertical (g) do casco, alinhada ao instante de contato.",
        "É a resposta dinâmica mais direta ao impacto; costuma ser o sinal usado para caracterizar a severidade do pouso.",
        "valor", "ensaio", "g"),
      it("C2", "Profundidade de submersão ao longo do tempo",
        "Registre até onde o casco afundou logo depois do pouso e como essa profundidade volta ao normal com o tempo.",
        "Série temporal de profundidade (m) desde o instante de contato até a estabilização.",
        "Mostra a resposta de flutuabilidade do casco, complementar à aceleração — um afundamento maior nem sempre corresponde a mais aceleração.",
        "valor", "ensaio", "m"),
      it("C3", "Oscilação do casco após o impacto",
        "Registre o quanto o casco balança de um lado para o outro (roll) e para frente/trás (pitch) depois do pouso, até parar de balançar.",
        "Amplitude de roll/pitch (°) ao longo do tempo pós-impacto.",
        "A oscilação residual indica o quanto de energia do impacto ficou \"guardada\" no movimento do casco em vez de ser amortecida.",
        "valor", "ensaio", "°"),
      it("C4", "Tempo até estabilização",
        "Cronometre quanto tempo o casco leva, depois do pouso, até parar de balançar e ficar estável na água. Defina antes um limite (por exemplo, oscilação menor que 2°) para considerar \"estável\".",
        "Tempo decorrido (s) entre o contato e o instante em que a oscilação cai abaixo do limite definido.",
        "Um número único resume a resposta transitória inteira e permite comparar ensaios entre si sem reanalisar toda a série temporal.",
        "valor", "ensaio", "s"),
    ],
  },
  {
    id: "D", titulo: "Identificação, separada da validação", core: true, categoria: "manobra",
    resumo: "Não usar o mesmo dado para ajustar o modelo e para provar que ele funciona.",
    itens: [
      it("D1", "Classificar a finalidade de cada ensaio",
        "Separe uma parte dos ensaios só para \"ensinar\" o modelo — ajustar seus parâmetros até ele bater com o que foi medido — e outra parte, nova, só para conferir se ele funciona.",
        "Rótulo \"identificação\" ou \"validação\" em cada linha da planilha de campo.",
        "Sem essa marcação, é fácil perder o controle de quais dados já foram \"vistos\" pelo modelo durante o ajuste.",
        "valor", "ensaio"),
      it("D2", "Nunca reaproveitar um ensaio nos dois grupos",
        "Um ensaio que serviu para ajustar o modelo não pode ser reaproveitado para provar que o modelo funciona — isso seria como corrigir a prova com a mesma pergunta usada para estudar.",
        "Confirmação de que os conjuntos de identificação e de validação não têm interseção.",
        "Reaproveitar dados de ajuste na validação superestima a qualidade do modelo (a métrica fica \"otimista\", e o modelo pode falhar em dados realmente novos).",
        "status", "sessao"),
      it("D3", "Documentar o critério de separação",
        "Anote, de forma simples, como você decidiu quais ensaios foram para identificação e quais foram para validação (por exemplo: 70% de cada condição para identificação, 30% novos para validação).",
        "Descrição textual do critério de particionamento dos dados, anexada ao protocolo.",
        "Permite que outra pessoa (ou você, meses depois) confira se a separação foi justa e reproduza o processo.",
        "valor", "sessao"),
    ],
  },
  {
    id: "E", titulo: "Estatística e condições", core: true, categoria: "manobra",
    resumo: "Garantir que o que foi observado é padrão, e não coincidência do dia.",
    itens: [
      it("E1", "Repetir cada ensaio pelo menos 10 vezes",
        "Precisamos repetir o mesmo ensaio 10 vezes porque aí conseguimos afirmar que os fenômenos observados são constantes e não fruto do acaso.",
        "Um conjunto de repetições que permite calcular uma média confiável e estimar o quanto o resultado varia de uma tentativa para outra (desvio-padrão).",
        "Com uma repetição só, não dá para saber se o resultado foi \"normal\" ou uma coincidência daquele dia. Repetir dá base estatística para separar padrão de ruído.",
        "valor", "sessao"),
      it("E2", "Aleatorizar a ordem de execução",
        "Não faça sempre a condição A, depois sempre a B, depois sempre a C. Embaralhe a ordem. Assim, se algo mudar ao longo do dia (vento aumentando, bateria cansando), esse efeito não fica \"colado\" em uma condição só.",
        "Sequência de execução dos ensaios sorteada, não fixa por condição.",
        "Sem aleatorização, uma tendência ao longo do tempo (deriva do equipamento, mudança de clima) se confunde com o efeito que está sendo estudado.",
        "status", "sessao"),
      it("E3", "Manter e registrar condições ambientais estáveis",
        "Tente repetir os ensaios em condições parecidas (vento, temperatura, estado do mar) e anote o que mudou. Se as condições variarem muito de uma repetição para outra, fica difícil saber se a diferença veio do que você está testando ou do ambiente.",
        "Registro de variação ambiental entre repetições do mesmo ensaio.",
        "Grande variação ambiental entre repetições aumenta o \"ruído\" e pode mascarar (ou simular) um efeito real.",
        "status", "sessao"),
      it("E4", "Definir o critério de sucesso/falha antes de rodar",
        "Decida, antes de começar, o que conta como \"passou\" e o que conta como \"falhou\" (por exemplo: pousou sem inverter, chegou ao ponto com erro menor que 1 m).",
        "Critério de sucesso/falha registrado no protocolo antes da coleta de dados.",
        "Definir o critério depois de ver o resultado abre espaço para julgar os dados a favor de uma conclusão, mesmo sem perceber.",
        "valor", "sessao"),
      it("E5", "Registrar o suficiente para alguém reproduzir o ensaio",
        "Anote tudo que uma outra pessoa precisaria saber para repetir exatamente o seu ensaio: configuração do veículo, local, número de repetições, condições.",
        "Checklist de itens mínimos de reprodutibilidade, preenchido junto ao protocolo.",
        "Se as instruções não bastam para outra pessoa reproduzir o ensaio, o resultado não pode ser confirmado de forma independente.",
        "status", "sessao"),
    ],
  },
  {
    id: "F", titulo: "Metadados por ensaio (planilha de campo)", core: true, categoria: "manobra",
    resumo: "Os campos abaixo viram as colunas da planilha que você preenche durante os ensaios.",
    itens: [
      it("F1", "ensaio_id", "Dê um número ou código único para cada ensaio, para nunca confundir um com outro depois.",
        "Chave única que identifica a linha na planilha de campo.", "Sem um identificador único, fica fácil duplicar ou perder o rastro de um ensaio ao juntar dados de fontes diferentes.",
        "valor", "ensaio"),
      it("F2", "data", "A data em que o ensaio foi realizado.",
        "Coluna de data (AAAA-MM-DD) na planilha de campo.", "Permite cruzar o ensaio com condições externas (clima, maré) e ordenar a sequência de execução.",
        "valor", "ensaio"),
      it("F3", "hora_gps", "A hora de início do ensaio, tirada do relógio do GPS (não do celular ou de cabeça).",
        "Coluna de hora absoluta de referência para alinhar com A2/A3.", "É a hora que efetivamente sincroniza com os timestamps dos logs de bordo.",
        "valor", "ensaio"),
      it("F4", "veiculo", "Qual veículo/protótipo foi usado neste ensaio (se houver mais de um).",
        "Coluna categórica identificando o veículo físico usado.", "Diferenças entre unidades do mesmo modelo (montagem, desgaste) podem afetar o resultado.",
        "valor", "ensaio"),
      it("F5", "placa_id", "Qual controladora/placa eletrônica específica estava instalada (útil quando há mais de uma unidade do mesmo modelo).",
        "Coluna categórica identificando a placa/controladora usada.", "Placas diferentes podem ter pequenas variações de calibração ou firmware que afetam a leitura.",
        "valor", "ensaio"),
      it("F6", "responsavel", "Quem executou ou registrou este ensaio.",
        "Coluna de autoria/registro por ensaio.", "Permite rastrear e esclarecer dúvidas sobre como um ensaio específico foi conduzido.",
        "valor", "ensaio"),
      it("F7", "local", "Onde o ensaio foi feito (tanque, praia, coordenadas).",
        "Coluna de local/coordenadas por ensaio.", "O local muda variáveis ambientais relevantes (correnteza, salinidade, espaço disponível).",
        "valor", "ensaio"),
      it("F8", "observacoes", "Qualquer coisa fora do comum que aconteceu durante o ensaio e vale a pena lembrar depois.",
        "Campo de texto livre por ensaio.", "Anomalias não previstas nos campos estruturados só ficam registradas se houver um lugar livre para anotá-las.",
        "valor", "ensaio"),
    ],
  },
  {
    id: "seguranca", titulo: "Segurança", fonte: "Guia HAUV · M1", categoria: "manobra",
    resumo: "Ler e confirmar antes de armar o veículo.",
    itens: [
      it("SEG1", "Distância mínima de 5 m durante o armamento",
        "Antes de ligar os motores, todo mundo precisa estar a pelo menos 5 metros de distância do veículo. Isso evita que alguém se machuque se uma hélice girar sem querer.",
        "Confirmação de distância mínima de segurança antes do armamento dos motores.",
        "O armamento pode acionar hélices de forma inesperada; a distância é a primeira barreira contra acidentes.",
        "tarefa", "ensaio"),
      it("SEG2", "Sem pessoas nem tráfego marítimo na área",
        "Olhe ao redor e confirme que não tem gente nem barcos passando perto de onde o ensaio vai acontecer.",
        "Verificação de área livre de terceiros antes do início do ensaio.",
        "Terceiros na área de operação não conhecem os riscos do ensaio e podem ser atingidos ou atrapalhar a execução.",
        "status", "sessao"),
      it("SEG3", "Estanqueidade verificada antes da imersão",
        "Confira que os compartimentos que não podem pegar água estão bem fechados antes de colocar o veículo na água.",
        "Checagem de vedação dos compartimentos estanques imediatamente antes da imersão.",
        "Um compartimento mal fechado pode alagar em segundos e comprometer eletrônica e flutuabilidade.",
        "status", "sessao"),
      it("SEG4", "Operador dedicado de recuperação aquática",
        "Precisa ter uma pessoa só cuidando de resgatar o veículo (ou uma pessoa) da água, sem fazer mais nada ao mesmo tempo.",
        "Alocação de um operador exclusivo para resgate em ensaios subaquáticos/de transição.",
        "Quem está operando o veículo não consegue, ao mesmo tempo, reagir rápido a uma emergência na água.",
        "tarefa", "ensaio"),
      it("SEG5", "Bateria carregada ≥ 90% no início",
        "Confira o nível de carga da bateria antes de começar — abaixo de 90% pode faltar energia no meio do ensaio.",
        "Confirmação do estado de carga mínimo antes do início do ensaio.",
        "Ficar sem energia em pleno ensaio (principalmente em voo) é um risco de segurança, não só de dados perdidos.",
        "status", "ensaio", "%"),
      it("SEG6", "Materiais necessários disponíveis e preparados",
        "Confira que tudo que vai ser usado (ferramentas, peças reservas, checklist impresso etc.) já está separado antes de começar.",
        "Checagem de prontidão logística antes do início da sessão.",
        "Interromper um ensaio no meio para buscar material aumenta o tempo de exposição a riscos e a chance de erro por pressa.",
        "tarefa", "sessao"),
    ],
  },
  {
    id: "mec", titulo: "Pré-ensaio — Estrutura mecânica", fonte: "Guia HAUV · M1", categoria: "manobra",
    resumo: "Inspeção mecânica antes de cada sessão.",
    itens: [
      it("MEC1", "Parafusos e juntas dos braços apertados", "Aperte à mão os parafusos dos braços; se algum estiver frouxo, o veículo pode vibrar ou até se soltar em operação.",
        "Verificação de torque/aperto das juntas estruturais.", "Folga estrutural altera a resposta dinâmica do veículo e pode evoluir para falha mecânica.", "status", "sessao"),
      it("MEC2", "Hélices aéreas sem danos ou folga", "Olhe e sinta as hélices aéreas: rachaduras ou folga no encaixe derrubam o desempenho e podem ser perigosas.",
        "Inspeção visual/tátil das hélices aéreas.", "Uma hélice danificada pode se romper em operação e desbalancear o veículo.", "status", "sessao"),
      it("MEC3", "Hélices subaquáticas sem danos ou folga", "Mesma checagem, mas nas hélices que giram dentro d'água.",
        "Inspeção visual/tátil das hélices subaquáticas.", "Danos nesse conjunto afetam empuxo e podem gerar vibração transmitida ao casco.", "status", "sessao"),
      it("MEC4", "Mecanismo de dobramento funcional (se aplicável)", "Se o veículo tem braços que dobram, teste se dobram e travam direito antes do ensaio.",
        "Teste funcional do mecanismo de dobra.", "Uma trava que falha em voo/mergulho muda a geometria do veículo de forma imprevista.", "status", "sessao"),
      it("MEC5", "Material de flutuação (espuma) íntegro", "Verifique se a espuma que ajuda o veículo a boiar não está rachada, amassada ou soltando pedaços.",
        "Inspeção do material de flutuabilidade.", "Perda de flutuabilidade muda o comportamento na água e pode comprometer a recuperação do veículo.", "status", "sessao"),
      it("MEC6", "Vedações dos compartimentos eletrônicos", "Confira se os anéis de vedação (o-rings) das caixas eletrônicas estão no lugar e sem cortes.",
        "Inspeção das vedações (o-rings) das caixas estanques.", "Vedação comprometida é a causa mais comum de alagamento de eletrônica.", "status", "sessao"),
      it("MEC7", "Cabos e conectores livres de corrosão", "Olhe os cabos e conectores procurando ferrugem ou esverdeado — sinal de que a água já entrou em algum lugar.",
        "Inspeção visual de corrosão em cabos e conectores.", "Corrosão aumenta resistência de contato e pode causar falha elétrica intermitente, difícil de diagnosticar depois.", "status", "sessao"),
      it("MEC8", "Distribuição de massa simétrica", "Veja se o peso está bem distribuído dos dois lados do veículo; desbalanceamento atrapalha o controle.",
        "Checagem de simetria de massa em relação ao eixo central.", "Assimetria de massa exige compensação contínua do controlador e pode limitar o desempenho.", "status", "sessao"),
      it("MEC9", "CG abaixo do CB (verificar no tanque)", "Coloque o veículo na água parado: o centro de gravidade precisa ficar abaixo do centro de flutuação, senão ele vira de cabeça para baixo.",
        "Verificação prática de estabilidade estática em tanque.", "CG acima do CB é uma condição de equilíbrio instável — o veículo tende a capotar sozinho.", "status", "sessao"),
      it("MEC10", "Braços dobráveis — ângulo de dobra correto (se aplicável)", "Confira se os braços dobráveis param no ângulo certo, nem mais aberto nem mais fechado do que deveriam.",
        "Verificação do ângulo final do mecanismo de dobra.", "Um ângulo fora da especificação muda a geometria aerodinâmica/hidrodinâmica prevista no projeto.", "status", "sessao"),
    ],
  },
  {
    id: "elet", titulo: "Pré-ensaio — Sistema eletrônico", fonte: "Guia HAUV · M1", categoria: "manobra",
    resumo: "Inspeção e calibração eletrônica antes de cada sessão.",
    itens: [
      it("ELE1", "Tensão da bateria ≥ 90%", "Meça a tensão real da bateria com o multímetro ou telemetria, não só a estimativa da porcentagem.",
        "Medição direta de tensão antes do início.", "A porcentagem estimada pode divergir da tensão real, especialmente em baterias mais usadas.", "status", "sessao", "V"),
      it("ELE2", "Calibração do IMU aéreo", "Calibre o sensor de movimento (IMU) da parte aérea seguindo o procedimento do fabricante.",
        "Calibração do sensor inercial do subsistema aéreo.", "Um IMU descalibrado introduz erro sistemático em toda leitura de atitude e aceleração.", "tarefa", "sessao"),
      it("ELE3", "Calibração do IMU subaquático", "Mesma calibração, mas no sensor de movimento da parte que vai para dentro d'água.",
        "Calibração do sensor inercial do subsistema subaquático.", "Mesmo risco do item anterior, aplicado ao conjunto que opera submerso.", "tarefa", "sessao"),
      it("ELE4", "Calibração da bússola", "Calibre a bússola longe de metal e ímãs, para as leituras de direção não saírem tortas.",
        "Calibração do magnetômetro.", "Interferência magnética não corrigida desalinha o rumo (heading) usado pelo controlador.", "tarefa", "sessao"),
      it("ELE5", "Fix de GPS (≥ 8 satélites)", "Antes de armar, confira que o GPS já está enxergando pelo menos 8 satélites — menos que isso, a posição fica imprecisa.",
        "Verificação da contagem de satélites e qualidade do fix antes do armamento.", "Um fix fraco aumenta o erro de posição, afetando tanto segurança quanto a qualidade dos dados de trajetória.", "status", "ensaio", "sats"),
      it("ELE6", "Parâmetros PID aéreo carregados", "Confirme que os parâmetros de controle (PID) do modo aéreo estão carregados na controladora, e não os de outro veículo.",
        "Checagem dos ganhos de controle carregados no firmware.", "Ganhos errados (de outro veículo/configuração) podem tornar o controle instável.", "status", "sessao"),
      it("ELE7", "Parâmetros S-plane/PID subaquático carregados", "Mesma confirmação, para os parâmetros de controle do modo subaquático.",
        "Checagem dos ganhos de controle do modo subaquático.", "Mesmo risco do item anterior, no subsistema subaquático.", "status", "sessao"),
      it("ELE8", "Sensor de profundidade — zero em superfície", "Com o veículo na superfície da água, zere o sensor de profundidade para as leituras começarem do lugar certo.",
        "Calibração do zero do sensor de pressão/profundidade.", "Um offset não corrigido desloca todas as leituras de profundidade do ensaio inteiro.", "tarefa", "ensaio"),
      it("ELE9", "Log de dados habilitado (SD/telemetria)", "Confirme que a gravação de dados está ligada antes de começar — sem isso, o ensaio não deixa registro.",
        "Confirmação de que o log está ativo e gravando antes do início do ensaio.", "É o requisito mais básico de todos: sem log, não há dado para analisar depois.", "status", "ensaio"),
      it("ELE10", "Link de rádio/Bluetooth operacional", "Teste o rádio ou Bluetooth de controle/telemetria antes de colocar o veículo em operação.",
        "Teste de comunicação antes do início da operação.", "Perda de link durante o ensaio pode impedir intervenção em caso de problema.", "status", "sessao"),
      it("ELE11", "ESCs aéreos — armamento testado em terra", "Teste o armamento dos motores aéreos em terra firme antes de ir para a água.",
        "Teste de armamento em bancada/terra antes da operação real.", "Detectar um problema de armamento em terra é seguro; detectá-lo já no ar ou na água, não.", "tarefa", "sessao"),
      it("ELE12", "ESCs subaquáticos — rotação testada em água", "Teste se os motores subaquáticos giram no sentido certo, já dentro d'água, antes do ensaio de verdade.",
        "Teste funcional de sentido de rotação em água.", "Rotação invertida em algum propulsor gera empuxo na direção errada e pode ser confundida com falha de controle.", "tarefa", "sessao"),
    ],
  },
  {
    id: "ambiente", titulo: "Condições ambientais", fonte: "Guia HAUV · M1", categoria: "manobra",
    resumo: "Registro do ambiente no momento do ensaio.",
    itens: [
      it("AMB1", "Data e hora", "Anote o dia e a hora em que o ensaio foi feito.", "Carimbo de data/hora do registro ambiental.", "Permite cruzar as condições com o restante do log do ensaio.", "valor", "ensaio"),
      it("AMB2", "Local (coordenadas GPS)", "Anote onde o ensaio foi feito, de preferência com coordenadas de GPS.", "Coordenadas do local do ensaio.", "O local influencia correnteza, salinidade e exposição ao vento.", "valor", "ensaio"),
      it("AMB3", "Velocidade do vento", "Meça a velocidade do vento no momento do ensaio; vento forte muda o comportamento do veículo.", "Medição de velocidade do vento.", "É uma das principais fontes de perturbação externa em ensaios ao ar livre.", "valor", "ensaio", "m/s"),
      it("AMB4", "Direção do vento", "Anote de onde o vento está vindo.", "Registro da direção do vento.", "A direção relativa ao veículo muda o tipo de perturbação (frontal, lateral).", "valor", "ensaio", "°"),
      it("AMB5", "Temperatura do ar", "Meça a temperatura do ar.", "Registro de temperatura ambiente.", "Afeta densidade do ar (empuxo aéreo) e desempenho da bateria.", "valor", "ensaio", "°C"),
      it("AMB6", "Temperatura da água (superfície)", "Meça a temperatura da água na superfície.", "Registro de temperatura da água.", "Afeta densidade da água e, indiretamente, a flutuabilidade.", "valor", "ensaio", "°C"),
      it("AMB7", "Estado do mar (escala WMO)", "Classifique o estado do mar numa escala padrão (0 = espelhado, aumentando com o tamanho das ondas).", "Classificação padronizada do estado do mar.", "Permite comparar ensaios de dias diferentes usando uma escala comum, em vez de uma descrição subjetiva.", "valor", "ensaio"),
      it("AMB8", "Altura de ondas (estimada)", "Estime a altura das ondas, mesmo que a olho.", "Estimativa de altura de onda.", "É uma perturbação direta sobre o pouso e a resposta do casco (Blocos B/C).", "valor", "ensaio", "m"),
      it("AMB9", "Salinidade", "Meça a salinidade da água, se tiver o instrumento.", "Registro de salinidade (PSU).", "Afeta a densidade da água e, portanto, a flutuabilidade e o empuxo medido.", "valor", "ensaio", "PSU"),
      it("AMB10", "Corrente de superfície", "Estime a velocidade da corrente de água na superfície.", "Registro de corrente de superfície.", "Corrente lateral pode ser confundida com efeito do próprio veículo se não for registrada.", "valor", "ensaio", "m/s"),
    ],
  },
  {
    id: "pos", titulo: "Pós-ensaio", fonte: "Guia HAUV · M7", categoria: "manobra",
    resumo: "Cuidados e registro logo depois do ensaio.",
    itens: [
      it("POS1", "Lavar com água doce (se ensaio em água salgada)", "Depois de um ensaio em água salgada, lave o veículo com água doce para tirar o sal antes que ele corroa as peças.",
        "Procedimento de descontaminação pós-ensaio.", "Sal residual acelera corrosão de contatos elétricos e partes metálicas.", "tarefa", "ensaio"),
      it("POS2", "Verificar integridade dos vedantes e caixas eletrônicas", "Depois do ensaio, confira de novo se não entrou água em nenhuma caixa eletrônica.",
        "Segunda inspeção de estanqueidade, agora pós-operação.", "Um vedante pode falhar sob pressão real, mesmo tendo passado na checagem antes do ensaio.", "status", "ensaio"),
      it("POS3", "Descarregar baterias para armazenamento (~50%)", "Se a bateria não for usada logo, descarregue até uns 50% antes de guardar — isso prolonga a vida dela.",
        "Procedimento de armazenamento de baterias LiPo/Li-ion.", "Guardar bateria cheia ou vazia por muito tempo reduz sua vida útil e pode ser um risco de segurança.", "tarefa", "sessao"),
      it("POS4", "Exportar e fazer backup dos logs", "Copie os arquivos de log do ensaio para um lugar seguro antes de apagar o cartão ou desligar tudo.",
        "Backup dos arquivos de log gerados no ensaio.", "É o único jeito de garantir que o esforço de campo não se perde por um cartão corrompido ou apagado.", "tarefa", "ensaio"),
      it("POS5", "Inspecionar hélices e propulsores por danos", "Olhe as hélices de novo depois do ensaio — impactos podem ter deixado marcas que não estavam lá antes.",
        "Segunda inspeção de hélices/propulsores, pós-operação.", "Detectar dano cedo evita que ele evolua e comprometa o próximo ensaio.", "status", "ensaio"),
      it("POS6", "Lubrificar pontos de giro dos braços dobráveis (se aplicável)", "Se o veículo tem dobradiças, passe lubrificante nos pontos de giro depois do uso em água salgada.",
        "Manutenção preventiva dos mecanismos móveis.", "Água salgada resseca e engripa mecanismos móveis se não forem lubrificados regularmente.", "tarefa", "sessao"),
      it("POS7", "Registrar falhas ou anomalias no diário", "Anote qualquer coisa estranha que aconteceu, mesmo pequena — isso ajuda a enxergar padrões ao longo do tempo.",
        "Registro textual de anomalias no diário de bordo do projeto.", "Eventos que parecem isolados podem, vistos em conjunto ao longo do tempo, revelar uma falha sistemática.", "tarefa", "sessao"),
    ],
  },

  // ───────────────────── CATEGORIA: BANCADA ─────────────────────
  {
    id: "banc_grandezas", titulo: "Grandezas medidas na bancada", categoria: "bancada",
    fonte: "SubHydrone/NAUTEC · Bancada Hydrone-J",
    resumo: "O que a bancada mede automaticamente durante a varredura — os dados brutos vão para o CSV, não são digitados à mão.",
    itens: [
      it("BN-G1", "Empuxo",
        "É a força que a hélice faz para 'empurrar'. A bancada mede por uma alavanca ligada a uma célula de carga (HX711).",
        "Série de leituras de força (kgf) por ponto de rotação, gravada em CSV pela bancada.",
        "É a principal variável de resposta do ensaio — é o que relaciona rotação e corrente ao desempenho útil do propulsor.",
        "status", "sessao", "kgf"),
      it("BN-G2", "Torque",
        "É o 'esforço de giro' do motor. Medido pela reação num braço preso a outra célula de carga.",
        "Série de torque (N·m) por ponto, gravada junto ao empuxo no mesmo CSV.",
        "Combinado com RPM, dá a potência mecânica entregue pelo eixo — essencial para calcular a eficiência do conjunto.",
        "status", "sessao", "N·m"),
      it("BN-G3", "RPM",
        "Quantas voltas por minuto a hélice dá. Um sensor Hall conta os pulsos do giro.",
        "Contagem de pulsos convertida em rpm, amostrada junto com as demais grandezas.",
        "É a variável que liga o comando de throttle ao comportamento físico real do propulsor — throttle e RPM nem sempre são proporcionais.",
        "status", "sessao", "rpm"),
      it("BN-G4", "Corrente total",
        "Quanta corrente o sistema puxa no total. É a base do cálculo de energia (ACS758 + INA219).",
        "Corrente total (A) amostrada continuamente, usada junto com a tensão para calcular potência elétrica.",
        "É o dado central do modelo de energia da bancada — sem ele não dá para calcular potência nem eficiência.",
        "status", "sessao", "A"),
      it("BN-G5", "Corrente de fase (3×)",
        "Corrente em cada uma das três fases do motor. Serve só para caracterizar o motor — não entra no modelo de energia.",
        "Três séries de corrente de fase (A), uma por enrolamento do motor BLDC.",
        "Ajuda a caracterizar o comportamento elétrico interno do motor, mas é informação complementar — o modelo de energia usa só a corrente total.",
        "status", "sessao", "A"),
      it("BN-G6", "Tensão",
        "A tensão de alimentação (INA219). Junto com a corrente total, dá a potência.",
        "Tensão de barramento (V), amostrada no mesmo instante que a corrente total.",
        "Tensão e corrente total juntas fecham o cálculo de potência elétrica instantânea.",
        "status", "sessao", "V"),
      it("BN-G7", "Potência elétrica",
        "Quanta energia por segundo o sistema gasta. Calculada de tensão × corrente total.",
        "Potência elétrica (W), calculada no pós-processamento a partir de tensão e corrente total.",
        "É a grandeza que permite comparar o custo energético de diferentes configurações de propulsor e rotação.",
        "status", "sessao", "W"),
      it("BN-G8", "Eficiência",
        "Quanto da energia gasta vira empuxo útil. Em RPM muito baixo do T200, os pontos são filtrados na análise — não na coleta.",
        "Eficiência (%) calculada como razão entre empuxo útil e potência elétrica consumida, por ponto de rotação.",
        "É a métrica que resume o desempenho do propulsor e permite comparar configurações de forma justa.",
        "status", "sessao", "%"),
      it("BN-G9", "Temperatura do motor (A CONFIRMAR)",
        "O quanto o motor esquenta durante o ensaio. Ainda não há sensor instalado — confirme antes de marcar.",
        "Série de temperatura (°C) do motor ao longo do ensaio, quando o sensor estiver instalado.",
        "Aquecimento excessivo pode alterar o desempenho do motor ao longo do ensaio e mascarar o efeito da rotação.",
        "status", "sessao", "°C"),
      it("BN-G10", "Velocidade do fluido, 3 posições (A CONFIRMAR)",
        "A velocidade do ar/água movimentado pela hélice, em três pontos. Ainda é trabalho futuro, não implementado.",
        "Perfil de velocidade do fluido (m/s) em três posições ao redor da hélice.",
        "Permitiria validar o modelo de empuxo a partir do escoamento, não só das grandezas elétricas — mas depende de instrumentação ainda não disponível.",
        "status", "sessao", "m/s"),
    ],
  },
  {
    id: "banc_fatores", titulo: "Fatores e níveis (o que você varia)", categoria: "bancada",
    fonte: "SubHydrone/NAUTEC · Bancada Hydrone-J",
    resumo: "O que você decide variar entre os ensaios: propulsor, rotação e a ordem de execução.",
    itens: [
      it("BN-F1", "Configuração de propulsor",
        "Qual propulsor está sendo testado. Cada um trabalha num meio: ML3508 no ar, T200 na água. Não comparamos ar × água diretamente — cada propulsor é analisado no seu meio.",
        "Rótulo da configuração testada (ML3508/ar, T200/submerso, ou DJI 2312/ar, opcional) registrado por sessão de ensaios.",
        "Propulsor e ambiente andam juntos (fatores confundidos) — por isso a comparação direta ar × água não é objetivo do ensaio.",
        "valor", "sessao"),
      it("BN-F2", "Rotação (throttle)",
        "O nível de aceleração. Você pode testar em três faixas (baixa ~20%, média ~50%, alta ~80%) ou usar a varredura contínua de 0 a 80% que a bancada já faz hoje. Confirme qual dos dois vai usar.",
        "Modo de variação de throttle escolhido para a sessão: 3 níveis fixos ou varredura contínua 0–80%.",
        "É o fator que mais mexe em empuxo, corrente e eficiência; a varredura contínua alimenta o ajuste polinomial (modelo paramétrico E1) e os 3 níveis servem para a ANOVA fatorial.",
        "valor", "sessao", "%"),
      it("BN-F3", "Repetições por ponto / janela de amostras",
        "Cada ponto é medido numa janela de 10 amostras seguidas (1 por segundo), e repetimos o ponto pelo menos 2 vezes. Repetir é o que permite dizer que o valor medido é real e não sorte do momento.",
        "Número de repetições por ponto e tamanho da janela de amostragem, registrados para a sessão.",
        "Réplicas dão a variância necessária para separar efeito real de ruído de medição.",
        "valor", "sessao"),
      it("BN-F4", "Ordem sorteada dos tratamentos (randomização)",
        "Antes de começar, sorteie a ordem dos 6 tratamentos (2 propulsores × 3 rotações). Isso evita que o aquecimento do motor ou uma mudança do ambiente ao longo do dia seja confundido com efeito do propulsor ou da rotação.",
        "Sequência sorteada dos 6 tratamentos, anexada ao protocolo antes da coleta.",
        "Randomização controla variáveis estranhas que variam no tempo (aquecimento, deriva ambiental).",
        "tarefa", "sessao"),
    ],
  },
  {
    id: "banc_prep_mec", titulo: "Preparação: estrutura mecânica", categoria: "bancada",
    fonte: "SubHydrone/NAUTEC · Bancada Hydrone-J",
    resumo: "Inspeção mecânica da bancada antes de cada sessão.",
    itens: [
      it("BN-PM1", "Bancada fixada, nivelada e travada na superfície de trabalho.",
        "Confirme que a bancada está presa e nivelada — se ela se mexer durante o ensaio, as medidas de empuxo e torque saem erradas.",
        "Confirmação de fixação e nivelamento da bancada antes do ensaio.",
        "Movimento da estrutura durante o ensaio introduz força espúria nas células de carga de empuxo e torque.",
        "status", "sessao"),
      it("BN-PM2", "Conjunto motor-hélice (ou propulsor T200) montado corretamente no eixo de tração.",
        "Confira que o motor com a hélice (ou o T200) está bem montado no eixo que a bancada usa para medir força.",
        "Verificação de montagem do conjunto de tração no eixo da bancada.",
        "Uma montagem frouxa ou desalinhada distorce a leitura de empuxo e pode danificar o eixo.",
        "status", "sessao"),
      it("BN-PM3", "Hélice (ou hélice do T200) balanceada, sem trincas, amassados ou danos visíveis.",
        "Olhe a hélice de perto: trincas, amassados ou desbalanceamento derrubam o desempenho e podem ser perigosos em alta rotação.",
        "Inspeção visual e de balanceamento da hélice antes do ensaio.",
        "Uma hélice danificada gera vibração que se mistura ao sinal de empuxo/torque e pode se romper em rotação alta.",
        "status", "sessao"),
      it("BN-PM4", "Sistema de alavanca (haste + célula de carga de empuxo) livre, sem atrito.",
        "Mexa a alavanca de empuxo à mão: ela precisa se mover livre, sem travar ou raspar em nada.",
        "Verificação de folga/atrito no sistema de alavanca de empuxo.",
        "Atrito no sistema de alavanca subestima sistematicamente o empuxo medido.",
        "status", "sessao"),
      it("BN-PM5", "Braço de reação (torque) alinhado, sem folgas mecânicas.",
        "Confira que o braço que mede o torque está alinhado e sem folga — folga faz o valor de torque pular ou ficar impreciso.",
        "Verificação de alinhamento e folga do braço de reação de torque.",
        "Folga mecânica introduz ruído e histerese na leitura de torque.",
        "status", "sessao"),
      it("BN-PM6", "Parafusos e fixações da estrutura de alumínio conferidos.",
        "Aperte e confira os parafusos da estrutura de alumínio da bancada antes de ligar qualquer coisa.",
        "Checagem de aperto das fixações estruturais da bancada.",
        "Uma fixação frouxa pode falhar sob vibração do motor em plena rotação, colocando o ensaio (e quem está por perto) em risco.",
        "status", "sessao"),
    ],
  },
  {
    id: "banc_prep_elet", titulo: "Preparação: instrumentação elétrica", categoria: "bancada",
    fonte: "SubHydrone/NAUTEC · Bancada Hydrone-J",
    resumo: "Preparação da instrumentação elétrica antes de cada sessão.",
    itens: [
      it("BN-PE1", "Bateria LiPo 4S carregada e sem inchaço ou dano.",
        "Confira a carga da bateria 4S e olhe se ela não está inchada ou danificada.",
        "Inspeção de carga e integridade física da bateria LiPo 4S.",
        "Bateria danificada ou descarregada compromete a segurança e introduz variação de tensão não controlada entre ensaios.",
        "status", "sessao"),
      it("BN-PE2", "Tensão da bateria medida com multímetro e registrada antes do ensaio.",
        "Meça a tensão real da bateria com o multímetro, não confie só na estimativa do carregador.",
        "Medição direta de tensão de bateria, registrada antes do início da sessão.",
        "A tensão real é o que efetivamente alimenta o motor — divergências da estimativa afetam corrente e potência medidas.",
        "status", "sessao", "V"),
      it("BN-PE3", "ESC conectado corretamente (polaridade da alimentação e sinal PWM).",
        "Confira a polaridade da alimentação e a ligação do sinal PWM no ESC antes de energizar.",
        "Verificação de conexão elétrica do ESC (alimentação e sinal PWM).",
        "Uma ligação invertida pode danificar o ESC ou o motor no instante em que a bancada armar.",
        "status", "sessao"),
      it("BN-PE4", "Placa STM32F407VET6 energizada e comunicando via serial.",
        "Confirme que a placa de controle está ligada e conversando pela serial com o computador.",
        "Verificação de energização e comunicação serial da placa STM32F407VET6.",
        "Sem comunicação serial confirmada, não há como saber se a bancada está de fato executando e registrando a sequência.",
        "status", "sessao"),
      it("BN-PE5", "Cartão SD inserido, formatado (FAT32) e com espaço livre suficiente.",
        "Confira que o cartão SD está encaixado, formatado em FAT32 e com espaço de sobra para o CSV do ensaio.",
        "Verificação de presença, formatação e espaço livre do cartão SD.",
        "Sem esse cartão em ordem, os dados brutos do ensaio simplesmente não são gravados.",
        "status", "sessao"),
      it("BN-PE6", "Relógio de tempo real (RTC) sincronizado com data e hora atuais.",
        "Sincronize o RTC da bancada com a data e hora reais antes de começar.",
        "Sincronização do relógio de tempo real (RTC) com a hora atual.",
        "Um RTC desacertado grava timestamps errados no nome do arquivo e no CSV, dificultando o rastreio depois.",
        "status", "sessao"),
    ],
  },
  {
    id: "banc_prep_sensores", titulo: "Preparação: sensores", categoria: "bancada",
    fonte: "SubHydrone/NAUTEC · Bancada Hydrone-J",
    resumo: "Calibração e checagem dos sensores da bancada antes de cada sessão.",
    itens: [
      it("BN-PS1", "INA219 (tensão de entrada, antes do ESC) respondendo via I2C.",
        "Confirme que o sensor de tensão INA219 está respondendo pela comunicação I2C antes de começar.",
        "Teste de comunicação I2C do INA219 de tensão de entrada.",
        "Sem esse sensor respondendo, a bancada não consegue calcular potência elétrica durante o ensaio.",
        "status", "sessao"),
      it("BN-PS2", "ACS758LCB-100B da corrente TOTAL instalado e com offset calibrado.",
        "Confira que o sensor de corrente total está instalado e com o offset (zero) calibrado.",
        "Verificação de instalação e calibração de offset do ACS758 de corrente total.",
        "Um offset não calibrado desloca todas as leituras de corrente do ensaio inteiro, mesmo que o formato da curva pareça certo.",
        "status", "sessao"),
      it("BN-PS3", "3× ACS758LCB-100B de corrente de FASE instalados nas três fases do motor BLDC.",
        "Confira que os três sensores de corrente de fase estão instalados, um em cada fase do motor.",
        "Verificação de instalação dos três sensores de corrente de fase do motor BLDC.",
        "Sem os três sensores, a caracterização elétrica do motor fica incompleta (mesmo não entrando no modelo de energia).",
        "status", "sessao"),
      it("BN-PS4", "Sensor Hall SNGQPLA-000 (RPM) e placa de contagem de pulsos operando.",
        "Confirme que o sensor Hall de RPM e a placa que conta os pulsos estão funcionando antes do ensaio.",
        "Teste funcional do sensor Hall e da placa de contagem de pulsos de RPM.",
        "Sem RPM confiável, não dá para relacionar throttle, empuxo, torque e eficiência entre si.",
        "status", "sessao"),
      it("BN-PS5", "2× células de carga (empuxo e torque) com HX711 calibradas (pesos-padrão 25/50/100 g).",
        "Calibre as duas células de carga (empuxo e torque) com os pesos-padrão de 25, 50 e 100 g antes do ensaio.",
        "Calibração das duas células de carga (HX711) com pesos-padrão de referência.",
        "Sem calibração recente com pesos conhecidos, os valores de empuxo e torque podem ter um erro de escala sistemático.",
        "status", "sessao"),
    ],
  },
  {
    id: "banc_seguranca", titulo: "Segurança da bancada", categoria: "bancada",
    fonte: "SubHydrone/NAUTEC · Bancada Hydrone-J",
    resumo: "Ler e confirmar antes de energizar a bancada.",
    itens: [
      it("BN-SG1", "Área de segurança ao redor da bancada demarcada e isolada.",
        "Demarque e isole a área ao redor da bancada antes de energizar qualquer coisa.",
        "Confirmação de demarcação e isolamento da área de segurança da bancada.",
        "Uma hélice em alta rotação pode arremessar fragmentos; a área isolada é a primeira barreira contra acidentes.",
        "status", "sessao"),
      it("BN-SG2", "Óculos de proteção disponíveis e em uso pelos operadores.",
        "Confirme que todo mundo perto da bancada está de óculos de proteção.",
        "Verificação de uso de EPI (óculos de proteção) pelos operadores.",
        "Protege contra fragmentos de hélice ou respingos em caso de falha mecânica.",
        "status", "sessao"),
      it("BN-SG3", "Corte de energia (botão de emergência ou desconexão rápida da bateria) acessível.",
        "Confirme que dá para cortar a energia rapidamente (botão de emergência ou desconexão da bateria) se algo der errado.",
        "Verificação de acessibilidade do corte de energia de emergência.",
        "Em uma falha mecânica ou elétrica, o tempo de reação para cortar energia é o que evita um dano maior.",
        "status", "sessao"),
      it("BN-SG4", "Rota de afastamento em caso de falha mecânica conhecida por todos os presentes.",
        "Combine com todo mundo por onde sair rápido se a hélice ou o motor falharem durante o ensaio.",
        "Confirmação de que a rota de afastamento é conhecida por todos os presentes.",
        "Decidir a rota de fuga depois que algo já quebrou custa tempo precioso.",
        "status", "sessao"),
      it("BN-SG5", "[Config. submersa] Tanque limpo, nível estável, propulsor a 0,5 m de profundidade e 0,5 m da parede.",
        "Na configuração submersa, confirme água limpa, nível estável e o propulsor a 0,5 m de profundidade e 0,5 m da parede do tanque.",
        "Verificação da geometria de imersão (profundidade e distância da parede) no ensaio submerso.",
        "Profundidade e distância de parede incorretas alteram o escoamento ao redor da hélice e distorcem a leitura de empuxo.",
        "status", "sessao"),
      it("BN-SG6", "[Config. submersa] Isolamento elétrico de todos os conectores verificado antes da imersão.",
        "Antes de colocar qualquer parte elétrica na água, confira que todos os conectores estão bem isolados.",
        "Verificação de isolamento elétrico de conectores antes da imersão.",
        "Um conector mal isolado pode causar curto-circuito ou choque no contato com a água.",
        "status", "sessao"),
    ],
  },
  {
    id: "banc_variaveis", titulo: "Controle de variáveis estranhas", categoria: "bancada",
    fonte: "SubHydrone/NAUTEC · Bancada Hydrone-J",
    resumo: "O que registrar e manter constante para não confundir efeito real com ruído do ambiente.",
    itens: [
      it("BN-VE1", "Temperatura ambiente registrada no início de cada bloco de tratamentos.",
        "Anote a temperatura ambiente no começo de cada bloco de tratamentos.",
        "Registro de temperatura ambiente (°C) no início de cada bloco de tratamentos.",
        "A temperatura ambiente pode afetar densidade do ar/água e o próprio desempenho do motor ao longo do dia.",
        "valor", "sessao", "°C"),
      it("BN-VE2", "Tensão da bateria conferida antes de cada tratamento (trocar se abaixo do limite seguro).",
        "Confira a tensão da bateria antes de cada tratamento e troque se estiver abaixo do limite seguro.",
        "Verificação de tensão de bateria antes de cada tratamento, com critério de troca definido.",
        "Uma bateria descarregando ao longo da sessão introduz uma tendência que pode se confundir com efeito da rotação testada.",
        "status", "sessao"),
      it("BN-VE3", "[Submersa] Nível de água e posição do propulsor mantidos constantes (0,5 m / 0,5 m).",
        "Na configuração submersa, mantenha sempre o mesmo nível de água e a mesma posição do propulsor entre tratamentos.",
        "Confirmação de constância da geometria de imersão entre tratamentos.",
        "Mudar a geometria de imersão entre tratamentos adiciona uma variável não controlada à comparação.",
        "status", "sessao"),
      it("BN-VE4", "Calibração dos instrumentos (células de carga, offset de corrente) conferida no início da sessão.",
        "No começo da sessão, confira de novo a calibração das células de carga e o offset de corrente.",
        "Checagem de calibração dos instrumentos no início da sessão de ensaios.",
        "Instrumentos descalibrados no início do dia comprometem todos os ensaios da sessão, não só um ponto isolado.",
        "status", "sessao"),
    ],
  },
  {
    id: "banc_metadados", titulo: "Metadados por ensaio (planilha de campo)", categoria: "bancada",
    fonte: "SubHydrone/NAUTEC · Bancada Hydrone-J",
    resumo: "Uma linha por ensaio. Os dados de sensor (RPM, empuxo, corrente…) não são digitados aqui — a bancada grava em CSV automaticamente; esta linha só aponta para esse arquivo.",
    itens: [
      it("BN-M1", "ensaio_id", "Dê um código único para este ensaio da bancada, para nunca confundir um arquivo CSV com outro depois.",
        "Chave única que identifica a linha na planilha de campo da bancada.", "Sem um identificador único, fica fácil perder o rastro de qual CSV corresponde a qual configuração testada.",
        "valor", "ensaio"),
      it("BN-M2", "data", "A data em que o ensaio de bancada foi realizado.",
        "Coluna de data (AAAA-MM-DD) na planilha de campo.", "Permite ordenar e cruzar os ensaios com o restante do diário de bancada.",
        "valor", "ensaio"),
      it("BN-M3", "configuração", "Qual propulsor e qual rotação (ou modo de varredura) foram usados neste ensaio.",
        "Coluna categórica com a combinação propulsor + rotação testada.", "É o elo entre a linha da planilha e o tratamento experimental que gerou aquele CSV.",
        "valor", "ensaio"),
      it("BN-M4", "nº de repetições por ponto", "Quantas vezes cada ponto de rotação foi repetido neste ensaio.",
        "Coluna numérica com o número de repetições por ponto.", "Registra, junto ao dado bruto, a base estatística que sustenta aquele ponto.",
        "valor", "ensaio"),
      it("BN-M5", "nome do arquivo CSV (SD)", "O nome exato do arquivo que a bancada gravou no cartão SD para este ensaio.",
        "Coluna de texto com o nome do arquivo bruto gerado pela bancada.", "É o vínculo direto entre a linha da planilha e o dado bruto real — sem ele a planilha vira só uma lista solta.",
        "valor", "ensaio"),
      it("BN-M6", "local do backup", "Onde você copiou o CSV depois de tirá-lo do cartão SD.",
        "Coluna de texto com o caminho/local do backup do arquivo.", "Garante que o dado bruto sobrevive mesmo se o cartão SD for reformatado ou perdido.",
        "valor", "ensaio"),
      it("BN-M7", "responsável", "Quem executou este ensaio de bancada.",
        "Coluna de autoria por ensaio.", "Permite esclarecer dúvidas sobre como um ensaio específico foi conduzido.",
        "valor", "ensaio"),
      it("BN-M8", "hora início", "A hora em que o ensaio começou.",
        "Coluna de hora de início por ensaio.", "Ajuda a cruzar o ensaio com condições ambientais e com o timestamp interno do CSV.",
        "valor", "ensaio"),
      it("BN-M9", "hora fim", "A hora em que o ensaio terminou.",
        "Coluna de hora de término por ensaio.", "Junto com a hora de início, dá a duração real do ensaio, útil para conferir se a varredura completou.",
        "valor", "ensaio"),
      it("BN-M10", "observações", "Qualquer coisa fora do comum que aconteceu durante o ensaio de bancada.",
        "Campo de texto livre por ensaio.", "Anomalias não previstas nos campos estruturados só ficam registradas se houver um lugar livre para anotá-las.",
        "valor", "ensaio"),
    ],
  },

  // ───────────────────── CATEGORIA: VEÍCULO ─────────────────────
  {
    id: "vei_fator_etapa", titulo: "Fator: etapa da missão (medidas repetidas, ordem fixa)", categoria: "veiculo",
    fonte: "SubHydrone/NAUTEC · Veículo Hydrone-J",
    resumo: "A missão híbrida acontece em 8 etapas numa ordem obrigatória — a réplica vem de repetir a missão inteira, não de embaralhar a ordem.",
    itens: [
      it("VJ-ET1", "Etapa da missão (8 níveis)",
        "A missão tem 8 etapas numa ordem obrigatória (Decolagem → Voo pairado → Deslocamento aéreo → Submersão → Deslocamento subaquático → Retorno à superfície → Retorno ao ponto de decolagem → Pouso). Não dá para sortear a ordem como na bancada.",
        "Registro de qual etapa da sequência fixa de 8 está sendo executada.",
        "A ordem das etapas é definida pela própria missão (não é um fator que se possa aleatorizar), então a análise trata a etapa como medida repetida dentro de cada execução.",
        "valor", "sessao"),
      it("VJ-ET2", "Nº de execuções completas (réplicas)",
        "Quantas vezes a missão inteira será repetida. Repetir a missão completa é o que dá base estatística para comparar as etapas entre si — não a troca de ordem das etapas.",
        "Número de execuções completas da missão planejadas para a sessão.",
        "Como a ordem das etapas é fixa, a réplica estatística vem de repetir a missão inteira, e não de reordenar etapas.",
        "valor", "sessao"),
    ],
  },
  {
    id: "vei_dados", titulo: "Requisitos de dados (variáveis de resposta)", categoria: "veiculo",
    fonte: "SubHydrone/NAUTEC · Veículo Hydrone-J",
    resumo: "O que precisa estar sendo registrado durante a missão para depois reconstruir e comparar as etapas.",
    itens: [
      it("VJ-D1", "Telemetria: posição, atitude, velocidade (A CONFIRMAR)",
        "Onde o veículo esteve, como estava orientado e a que velocidade. Serve para reconstruir a trajetória e reproduzir a missão em simulação (BiguaSim). Confirme formato, frequência e fonte antes de marcar.",
        "Série temporal de posição, atitude e velocidade, em formato e frequência ainda a definir.",
        "É a base para reconstruir a trajetória real da missão e comparar com a simulação em BiguaSim.",
        "status", "sessao"),
      it("VJ-D2", "Corrente da bateria (A CONFIRMAR)",
        "Consumo medido no terminal da bateria. Confirme se é ponto de medição diferente da corrente do sistema.",
        "Medição de corrente no terminal da bateria, se confirmado como ponto de medição distinto.",
        "Divergências entre corrente da bateria e corrente do sistema podem indicar perdas ou pontos de medição não equivalentes.",
        "status", "sessao"),
      it("VJ-D3", "Corrente do sistema (total)",
        "Corrente total entre bateria e ESC — mesma convenção da bancada, base do modelo de energia. Nunca a corrente de fase. (INA219 + ACS758, embarcados.)",
        "Corrente total (A) do sistema, amostrada continuamente durante toda a missão.",
        "É a mesma convenção usada na bancada — mantém o modelo de energia consistente entre bancada e campo.",
        "valor", "sessao", "A"),
      it("VJ-D4", "Tensão do sistema",
        "A tensão do sistema (INA219). Com a corrente total, permite calcular a potência.",
        "Tensão de barramento (V) do sistema, amostrada continuamente.",
        "Tensão e corrente total juntas fecham o cálculo de potência elétrica por etapa.",
        "valor", "sessao", "V"),
      it("VJ-D5", "Potência elétrica",
        "Calculada (V × I total) por etapa, no pós-processamento.",
        "Potência elétrica (W) por etapa, calculada a partir da tensão e corrente total registradas.",
        "Permite comparar o custo energético de cada etapa da missão entre si e entre execuções.",
        "valor", "sessao", "W"),
      it("VJ-D6", "Timestamp / sincronismo (A CONFIRMAR)",
        "Um relógio único entre o sistema embarcado e o log de telemetria, para alinhar dados e marcar início/fim de cada etapa.",
        "Sincronização de timestamp entre o sistema embarcado e o log de telemetria, em método ainda a confirmar.",
        "Sem um relógio comum, não dá para saber com certeza onde uma etapa termina e a próxima começa nos dados registrados.",
        "status", "sessao"),
    ],
  },
  {
    id: "vei_prep_veiculo", titulo: "Preparação: veículo", categoria: "veiculo",
    fonte: "SubHydrone/NAUTEC · Veículo Hydrone-J",
    resumo: "Inspeção do veículo antes do ensaio de campo.",
    itens: [
      it("VJ-PV1", "Casco e vedações íntegros, sem trincas ou folgas.",
        "Confira o casco e as vedações antes de ir para a água — trincas ou folgas comprometem a estanqueidade.",
        "Inspeção visual do casco e das vedações antes da missão.",
        "Um casco ou vedação comprometidos podem alagar a eletrônica durante a etapa submersa.",
        "status", "sessao"),
      it("VJ-PV2", "Bateria(s) (Tattu 4S1P 2300 mAh) carregada(s) e sem dano.",
        "Confira a carga e a integridade física das baterias Tattu 4S1P antes da missão.",
        "Inspeção de carga e integridade das baterias antes da missão.",
        "Uma bateria comprometida é ao mesmo tempo um risco de segurança e uma fonte de energia insuficiente para completar as 8 etapas.",
        "status", "sessao"),
      it("VJ-PV3", "Hélices (conjunto aéreo) e propulsor T200 (conjunto submerso) fixados e balanceados.",
        "Confira que as hélices aéreas e o T200 estão bem fixados e balanceados antes de decolar.",
        "Inspeção de fixação e balanceamento dos conjuntos aéreo e submerso.",
        "Desbalanceamento em qualquer um dos conjuntos afeta o controle nas duas fases da missão.",
        "status", "sessao"),
      it("VJ-PV4", "Firmware/software na versão validada em bancada antes do ensaio de campo.",
        "Confirme que o veículo está com a mesma versão de firmware/software já testada em bancada, e não uma versão experimental nova.",
        "Verificação da versão de firmware/software carregada, comparada à validada em bancada.",
        "Testar em campo uma versão não validada mistura risco de firmware com o que se está tentando medir na missão.",
        "status", "sessao"),
    ],
  },
  {
    id: "vei_prep_instrumentacao", titulo: "Preparação: instrumentação embarcada", categoria: "veiculo",
    fonte: "SubHydrone/NAUTEC · Veículo Hydrone-J",
    resumo: "Checagem da instrumentação elétrica embarcada antes da missão.",
    itens: [
      it("VJ-PI1", "INA219 de tensão instalado no barramento entre a bateria e o ESC.",
        "Confirme que o sensor de tensão está instalado no ponto certo, entre a bateria e o ESC.",
        "Verificação de instalação do INA219 no barramento entre bateria e ESC.",
        "Instalado no ponto errado, o sensor mede uma tensão que não representa o que chega de fato ao ESC.",
        "status", "sessao"),
      it("VJ-PI2", "ACS758LCB-100B de corrente TOTAL no mesmo barramento.",
        "Confirme que o sensor de corrente total está no mesmo barramento do sensor de tensão.",
        "Verificação de instalação do ACS758 de corrente total no barramento correto.",
        "Tensão e corrente precisam ser medidas no mesmo ponto para o cálculo de potência fazer sentido.",
        "status", "sessao"),
      it("VJ-PI3", "Armazenamento embarcado (SD/telemetria) funcionando e com espaço livre.",
        "Confira que o armazenamento embarcado está funcionando e com espaço de sobra para a missão inteira.",
        "Verificação de funcionamento e espaço livre do armazenamento embarcado.",
        "Ficar sem espaço no meio da missão significa perder dados justamente das últimas etapas.",
        "status", "sessao"),
      it("VJ-PI4", "Horário do sistema embarcado sincronizado com o horário da equipe em solo.",
        "Sincronize o relógio do sistema embarcado com o horário da equipe em solo antes de começar.",
        "Sincronização de horário entre o sistema embarcado e a equipe em solo.",
        "Sem essa sincronização, fica difícil cruzar o log embarcado com anotações e observações feitas em solo.",
        "status", "sessao"),
    ],
  },
  {
    id: "vei_ambiente", titulo: "Ambiente e logística", categoria: "veiculo",
    fonte: "SubHydrone/NAUTEC · Veículo Hydrone-J",
    resumo: "Condições e organização da equipe antes de posicionar o veículo.",
    itens: [
      it("VJ-AL1", "Condições climáticas dentro dos limites operacionais [a confirmar].",
        "Confira se o clima do dia está dentro do que o veículo suporta operar — os limites exatos ainda precisam ser confirmados com a equipe.",
        "Verificação de condições climáticas frente a limites operacionais a serem definidos.",
        "Operar fora dos limites (vento, chuva) aumenta o risco de acidente e pode invalidar a comparação entre execuções.",
        "status", "sessao"),
      it("VJ-AL2", "Estado do corpo d'água adequado para o ensaio no local [a confirmar].",
        "Confira se as condições da água (ondulação, corrente) estão adequadas para o ensaio no local escolhido — o critério exato ainda precisa ser confirmado.",
        "Verificação do estado do corpo d'água frente a um critério de adequação a ser definido.",
        "Água muito agitada pode alterar o comportamento da etapa submersa de um jeito que não é o que se quer medir.",
        "status", "sessao"),
      it("VJ-AL3", "Equipe de apoio posicionada (operador/piloto, resgate aquático, registro).",
        "Confirme que todo mundo da equipe de apoio já está no lugar certo antes de começar: quem pilota, quem resgata, quem registra.",
        "Confirmação de posicionamento da equipe de apoio antes da missão.",
        "Faltando alguém da equipe, a missão não pode ser interrompida com segurança em caso de problema.",
        "status", "sessao"),
      it("VJ-AL4", "Área de decolagem e ponto de entrada na água livres de obstáculos e sinalizados.",
        "Confira que a área de decolagem e o ponto de entrada na água estão livres de obstáculos e sinalizados.",
        "Verificação de área de decolagem e ponto de entrada livres e sinalizados.",
        "Obstáculos não sinalizados na decolagem ou na entrada na água são uma causa comum de acidente evitável.",
        "status", "sessao"),
    ],
  },
  {
    id: "vei_seguranca", titulo: "Segurança (campo)", categoria: "veiculo",
    fonte: "SubHydrone/NAUTEC · Veículo Hydrone-J",
    resumo: "Ler e confirmar antes de posicionar o veículo para a primeira etapa.",
    itens: [
      it("VJ-SC1", "Equipamento de flutuação individual disponível para a equipe.",
        "Confirme que todo mundo da equipe tem colete ou equipamento de flutuação disponível.",
        "Verificação de disponibilidade de equipamento de flutuação individual.",
        "Ensaios com entrada na água exigem que a equipe esteja protegida, não só o veículo.",
        "status", "sessao"),
      it("VJ-SC2", "Comunicação por rádio entre operadores testada antes do início.",
        "Teste o rádio entre os operadores antes de começar a primeira etapa.",
        "Teste de comunicação por rádio entre operadores.",
        "Perder comunicação durante uma etapa submersa ou de deslocamento pode atrasar uma resposta de emergência.",
        "status", "sessao"),
      it("VJ-SC3", "Plano de contingência para perda de comunicação conhecido pela equipe.",
        "Combine com a equipe o que fazer se a comunicação cair no meio de uma etapa.",
        "Confirmação de que o plano de contingência de comunicação é conhecido pela equipe.",
        "Decidir o plano de contingência durante a emergência, e não antes, custa tempo de reação.",
        "status", "sessao"),
      it("VJ-SC4", "Kit de primeiros socorros disponível no local.",
        "Confirme que o kit de primeiros socorros está no local antes de começar.",
        "Verificação de disponibilidade do kit de primeiros socorros.",
        "É a resposta mínima para um incidente leve com a equipe, sem depender de buscar ajuda longe do local.",
        "status", "sessao"),
    ],
  },
  {
    id: "vei_variaveis", titulo: "Controle de variáveis estranhas (campo)", categoria: "veiculo",
    fonte: "SubHydrone/NAUTEC · Veículo Hydrone-J",
    resumo: "O que manter constante entre execuções para poder comparar as etapas entre si de forma justa.",
    itens: [
      it("VJ-VC1", "Condições ambientais (vento, estado do corpo d'água) registradas no início de cada execução.",
        "Anote as condições ambientais (vento, estado da água) no início de cada execução completa da missão.",
        "Registro de condições ambientais no início de cada execução completa.",
        "Sem esse registro, uma mudança de vento entre execuções pode ser confundida com diferença de desempenho entre etapas.",
        "valor", "sessao"),
      it("VJ-VC2", "Carga da bateria e integridade do casco conferidas antes de cada execução.",
        "Confira a carga da bateria e a integridade do casco antes de cada execução completa da missão.",
        "Checagem de bateria e casco antes de cada execução.",
        "Uma bateria mais fraca ou um casco comprometido em execuções tardias vicia a comparação com as primeiras execuções do dia.",
        "status", "sessao"),
      it("VJ-VC3", "Mesmo ponto de decolagem e mesma rota planejada em todas as execuções.",
        "Use sempre o mesmo ponto de decolagem e a mesma rota planejada em todas as execuções.",
        "Confirmação de constância do ponto de decolagem e da rota entre execuções.",
        "Mudar o ponto de partida ou a rota introduz uma variável não controlada na comparação entre execuções.",
        "status", "sessao"),
      it("VJ-VC4", "Mesma versão de firmware/software entre execuções da mesma série de réplicas.",
        "Não troque a versão de firmware/software no meio de uma série de execuções que serão comparadas entre si.",
        "Confirmação de que a versão de firmware/software não mudou durante a série de réplicas.",
        "Trocar de versão no meio da série mistura o efeito da mudança de software com a variação natural entre execuções.",
        "status", "sessao"),
    ],
  },
  {
    id: "vei_metadados", titulo: "Metadados por etapa (planilha de campo)", categoria: "veiculo",
    fonte: "SubHydrone/NAUTEC · Veículo Hydrone-J",
    resumo: "Uma linha por etapa de cada execução (8 etapas por missão completa). Liga cada arquivo bruto de telemetria/energia à etapa e à execução certas.",
    itens: [
      it("VJ-M1", "ensaio_id (execução)", "Dê um código único para cada execução completa da missão (não para cada etapa).",
        "Chave única que identifica a execução na planilha de campo.", "Como cada execução tem 8 linhas (uma por etapa), esse código é o que agrupa as 8 etapas de uma mesma missão.",
        "valor", "ensaio"),
      it("VJ-M2", "etapa (1–8)", "O número da etapa dentro da execução (1 a 8), sempre na ordem fixa da missão.",
        "Coluna numérica indicando qual das 8 etapas fixas está sendo registrada.", "Permite separar e comparar o desempenho de cada etapa entre execuções diferentes.",
        "valor", "ensaio"),
      it("VJ-M3", "data", "A data em que a execução foi realizada.",
        "Coluna de data (AAAA-MM-DD) na planilha de campo.", "Permite cruzar a execução com condições externas e ordenar as execuções no tempo.",
        "valor", "ensaio"),
      it("VJ-M4", "condição ambiental", "Um resumo curto da condição ambiental durante essa etapa (vento, estado da água).",
        "Coluna de texto com a condição ambiental observada na etapa.", "Serve de referência rápida sem precisar abrir o registro detalhado do bloco de variáveis estranhas.",
        "valor", "ensaio"),
      it("VJ-M5", "local", "Onde a execução foi feita (área de decolagem/entrada na água).",
        "Coluna de local/coordenadas por execução.", "O local muda variáveis relevantes como correnteza e espaço disponível para a etapa submersa.",
        "valor", "ensaio"),
      it("VJ-M6", "hora início da etapa", "A hora em que essa etapa específica começou.",
        "Coluna de hora de início por etapa.", "Permite calcular a duração de cada etapa e alinhar com o log de telemetria.",
        "valor", "ensaio"),
      it("VJ-M7", "hora fim da etapa", "A hora em que essa etapa específica terminou.",
        "Coluna de hora de término por etapa.", "Junto com a hora de início, dá a duração real de cada etapa dentro da execução.",
        "valor", "ensaio"),
      it("VJ-M8", "arquivo de dados", "O nome do arquivo de telemetria/energia que corresponde a essa etapa.",
        "Coluna de texto com o nome do arquivo bruto de dados da etapa.", "É o vínculo direto entre a linha da planilha e o dado bruto real gerado durante aquela etapa.",
        "valor", "ensaio"),
      it("VJ-M9", "responsável", "Quem executou ou registrou essa etapa.",
        "Coluna de autoria/registro por etapa.", "Permite esclarecer dúvidas sobre como uma etapa específica foi conduzida.",
        "valor", "ensaio"),
      it("VJ-M10", "observações", "Qualquer coisa fora do comum que aconteceu durante essa etapa.",
        "Campo de texto livre por etapa.", "Anomalias específicas de uma etapa (não da execução inteira) só ficam registradas se houver um campo livre para isso.",
        "valor", "ensaio"),
    ],
  },
];

// Sugestão de ordem de execução em campo (aparece no topo do plano gerado), por categoria.
export const ORDEM_SUGERIDA = {
  manobra: [
    { bloco: "seguranca", nota: "Confirme segurança antes de qualquer outra coisa." },
    { bloco: "mec", nota: "Inspeção mecânica." },
    { bloco: "elet", nota: "Inspeção e calibração eletrônica." },
    { bloco: "ambiente", nota: "Registre as condições ambientais do dia." },
    { bloco: "A", nota: "Confirme a base de tempo comum antes do primeiro ensaio." },
    { bloco: "E", nota: "Relembre o critério de sucesso/falha e a ordem aleatorizada dos ensaios." },
    { bloco: "B", nota: "Durante cada ensaio: registre a entrada/perturbação do pouso." },
    { bloco: "C", nota: "Durante cada ensaio: registre a resposta do casco." },
    { bloco: "F", nota: "Preencha os metadados de cada ensaio na planilha de campo." },
    { bloco: "D", nota: "Ao fim da sessão: classifique os ensaios em identificação/validação." },
    { bloco: "pos", nota: "Procedimentos de pós-ensaio." },
  ],
  bancada: [
    { bloco: "banc_seguranca", nota: "Confirme a segurança da bancada antes de energizar qualquer coisa." },
    { bloco: "banc_prep_mec", nota: "Inspecione e trave a estrutura mecânica." },
    { bloco: "banc_prep_elet", nota: "Prepare a instrumentação elétrica: inicialize periféricos (serial, I2C, RTC, cartão SD)." },
    { bloco: "banc_prep_sensores", nota: "Calibre e inicialize os sensores (células de carga, INA219, RPM) antes de armar o ESC." },
    { bloco: "banc_fatores", nota: "Defina a configuração de propulsor e a rotação do ensaio; sorteie a ordem dos tratamentos." },
    { bloco: "banc_variaveis", nota: "Registre temperatura ambiente e tensão da bateria antes de iniciar a varredura." },
    { bloco: "banc_grandezas", nota: "Acione o botão físico e rode a varredura de throttle 0–80% (STARTBIT→SETPOINT→RAMPA→ESPERA→STOPBIT); a bancada grava empuxo, torque, RPM, corrente e tensão em CSV." },
    { bloco: "banc_metadados", nota: "Ao final, desarme o ESC, retire o cartão SD e preencha a linha da planilha de campo com o nome do arquivo e o backup." },
  ],
  veiculo: [
    { bloco: "vei_seguranca", nota: "Confirme a checklist de segurança de campo antes de qualquer etapa." },
    { bloco: "vei_prep_veiculo", nota: "Confira a preparação do veículo (casco, baterias, hélices, firmware validado em bancada)." },
    { bloco: "vei_prep_instrumentacao", nota: "Confirme a instrumentação embarcada e o sincronismo de horário antes de posicionar o veículo." },
    { bloco: "vei_ambiente", nota: "Verifique ambiente e logística e posicione o veículo no ponto de partida da etapa." },
    { bloco: "vei_fator_etapa", nota: "Execute a etapa da missão na ordem fixa (1 a 8), sem randomizar." },
    { bloco: "vei_variaveis", nota: "Registre condições ambientais e integridade antes de cada execução completa." },
    { bloco: "vei_dados", nota: "Durante a etapa, registre tensão e corrente total continuamente, sem interrupções." },
    { bloco: "vei_metadados", nota: "Ao encerrar a etapa, retorne a condição segura e faça backup imediato, preenchendo a linha da planilha por etapa." },
  ],
};

const STORAGE_KEY = "hep:requisitos:v1";

function comCategoria(bloco) {
  return bloco.categoria ? bloco : { ...bloco, categoria: CATEGORIA_PADRAO };
}

export function loadBlocos() {
  let saved = null;
  try {
    const parsed = JSON.parse(window.localStorage.getItem(STORAGE_KEY) || "null");
    if (Array.isArray(parsed) && parsed.length) saved = parsed;
  } catch { /* ignora e usa o padrão */ }
  if (!saved) return BLOCOS_PADRAO;
  const migrado = saved.map(comCategoria);
  const idsExistentes = new Set(migrado.map(b => b.id));
  const faltando = BLOCOS_PADRAO.filter(b => !idsExistentes.has(b.id));
  return faltando.length ? [...migrado, ...faltando] : migrado;
}
export function saveBlocos(blocos) {
  try { window.localStorage.setItem(STORAGE_KEY, JSON.stringify(blocos)); } catch { /* localStorage indisponível */ }
}
export function resetBlocos() {
  try { window.localStorage.removeItem(STORAGE_KEY); } catch { /* localStorage indisponível */ }
  return BLOCOS_PADRAO;
}
export function novoItemVazio() {
  return it(uid(), "", "", "", "", "valor", "ensaio");
}
export function novoBlocoVazio(categoria = CATEGORIA_PADRAO) {
  return { id: uid(), titulo: "Novo bloco", resumo: "", categoria, itens: [] };
}
