// Motor estatístico e utilitários genéricos (extraídos do app original, sem mudanças de comportamento).

export const mean = a => a.reduce((x, y) => x + y, 0) / a.length;
export const variance = a => { const m = mean(a); return a.reduce((x, y) => x + (y - m) ** 2, 0) / (a.length - 1); };
export const std = a => a.length > 1 ? Math.sqrt(variance(a)) : 0;
export const median = a => { const s = [...a].sort((x, y) => x - y); const n = s.length; return n % 2 ? s[(n - 1) / 2] : (s[n / 2 - 1] + s[n / 2]) / 2; };

function gammaln(x) { const c = [76.18009172947146, -86.50532032941677, 24.01409824083091, -1.231739572450155, 0.1208650973866179e-2, -0.5395239384953e-5]; let y = x, tmp = x + 5.5; tmp -= (x + 0.5) * Math.log(tmp); let ser = 1.000000000190015; for (let j = 0; j < 6; j++) { y++; ser += c[j] / y; } return -tmp + Math.log(2.5066282746310005 * ser / x); }
function betacf(a, b, x) { const MAXIT = 200, EPS = 3e-12, FPMIN = 1e-300; let qab = a + b, qap = a + 1, qam = a - 1, c = 1, d = 1 - qab * x / qap; if (Math.abs(d) < FPMIN) d = FPMIN; d = 1 / d; let h = d; for (let m = 1; m <= MAXIT; m++) { const m2 = 2 * m; let aa = m * (b - m) * x / ((qam + m2) * (a + m2)); d = 1 + aa * d; if (Math.abs(d) < FPMIN) d = FPMIN; c = 1 + aa / c; if (Math.abs(c) < FPMIN) c = FPMIN; d = 1 / d; h *= d * c; aa = -(a + m) * (qab + m) * x / ((a + m2) * (qap + m2)); d = 1 + aa * d; if (Math.abs(d) < FPMIN) d = FPMIN; c = 1 + aa / c; if (Math.abs(c) < FPMIN) c = FPMIN; d = 1 / d; const del = d * c; h *= del; if (Math.abs(del - 1) < EPS) break; } return h; }
function betai(a, b, x) { if (x <= 0) return 0; if (x >= 1) return 1; const bt = Math.exp(gammaln(a + b) - gammaln(a) - gammaln(b) + a * Math.log(x) + b * Math.log(1 - x)); return x < (a + 1) / (a + b + 2) ? bt * betacf(a, b, x) / a : 1 - bt * betacf(b, a, 1 - x) / b; }
const fPValue = (F, d1, d2) => F <= 0 ? 1 : betai(d2 / 2, d1 / 2, d2 / (d2 + d1 * F));
function gammp(a, x) { if (x <= 0 || a <= 0) return 0; if (x < a + 1) { let ap = a, sum = 1 / a, del = sum; for (let n = 0; n < 300; n++) { ap++; del *= x / ap; sum += del; if (Math.abs(del) < Math.abs(sum) * 1e-13) break; } return sum * Math.exp(-x + a * Math.log(x) - gammaln(a)); } const FPMIN = 1e-300; let b = x + 1 - a, c = 1 / FPMIN, d = 1 / b, h = d; for (let i = 1; i <= 300; i++) { const an = -i * (i - a); b += 2; d = an * d + b; if (Math.abs(d) < FPMIN) d = FPMIN; c = b + an / c; if (Math.abs(c) < FPMIN) c = FPMIN; d = 1 / d; const del = d * c; h *= del; if (Math.abs(del - 1) < 1e-13) break; } return 1 - Math.exp(-x + a * Math.log(x) - gammaln(a)) * h; }
const chiSqP = (x, df) => x <= 0 || df <= 0 ? 1 : 1 - gammp(df / 2, x / 2);

export function oneWayAnova(groups) { const keys = Object.keys(groups); const all = keys.flatMap(k => groups[k]); const N = all.length, k = keys.length, grand = mean(all); let ssb = 0, ssw = 0; keys.forEach(key => { const g = groups[key], gm = mean(g); ssb += g.length * (gm - grand) ** 2; g.forEach(v => ssw += (v - gm) ** 2); }); const dfb = k - 1, dfw = N - k, msb = ssb / dfb, msw = ssw / dfw, F = msb / msw; return { ssb, ssw, sst: ssb + ssw, dfb, dfw, msb, msw, F, p: fPValue(F, dfb, dfw), k, N }; }
export function kruskalWallis(groups) { const keys = Object.keys(groups); const all = []; keys.forEach(k => groups[k].forEach(v => all.push({ v, k }))); const N = all.length; all.sort((a, b) => a.v - b.v); let i = 0; while (i < N) { let j = i; while (j + 1 < N && all[j + 1].v === all[i].v) j++; const rank = (i + j + 2) / 2; for (let m = i; m <= j; m++) all[m].rank = rank; i = j + 1; } const Rsum = {}, ns = {}; keys.forEach(k => { Rsum[k] = 0; ns[k] = 0; }); all.forEach(o => { Rsum[o.k] += o.rank; ns[o.k]++; }); let H = 0; keys.forEach(k => H += Rsum[k] ** 2 / ns[k]); H = 12 / (N * (N + 1)) * H - 3 * (N + 1); const df = keys.length - 1; return { H, df, p: chiSqP(H, df), N, k: keys.length }; }
export function chiSquareTest(groups) { const gKeys = Object.keys(groups); const cats = [...new Set(gKeys.flatMap(g => groups[g]))]; const obs = {}, rowTot = {}, colTot = {}; let N = 0; gKeys.forEach(g => { obs[g] = {}; rowTot[g] = 0; cats.forEach(c => obs[g][c] = 0); groups[g].forEach(v => { obs[g][v]++; rowTot[g]++; N++; }); }); cats.forEach(c => colTot[c] = gKeys.reduce((s, g) => s + obs[g][c], 0)); let X2 = 0; gKeys.forEach(g => cats.forEach(c => { const E = rowTot[g] * colTot[c] / N; if (E > 0) X2 += (obs[g][c] - E) ** 2 / E; })); const df = (gKeys.length - 1) * (cats.length - 1); return { X2, df, p: df > 0 ? chiSqP(X2, df) : 1, obs, cats, gKeys, rowTot, colTot, N }; }

export const shuffle = arr => { const a = [...arr]; for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1));[a[i], a[j]] = [a[j], a[i]]; } return a; };
export function toCSV(rows, cols) { const esc = v => { const s = v == null ? "" : String(v); return /[",\n]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s; }; return [cols.join(","), ...rows.map(r => cols.map(c => esc(r[c])).join(","))].join("\n"); }
export function download(name, content, type) { const blob = new Blob([content], { type: type || "text/csv;charset=utf-8;" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); }
export const coerce = v => { const t = String(v).trim(); return t !== "" && !isNaN(Number(t)) ? Number(t) : v; };

export const LS = (() => { const mem = {}; return { get: k => { try { return window.localStorage.getItem(k); } catch { return k in mem ? mem[k] : null; } }, set: (k, v) => { try { window.localStorage.setItem(k, v); } catch { mem[k] = v; } }, del: k => { try { window.localStorage.removeItem(k); } catch { delete mem[k]; } } }; })();
export const readJSON = (k, fb) => { try { const v = LS.get(k); return v ? JSON.parse(v) : fb; } catch { return fb; } };
export const writeJSON = (k, v) => LS.set(k, JSON.stringify(v));
